#!/bin/bash
set -eou pipefail
cd "$(dirname "$0")/.."

echo "==> autoflake"
poetry run autoflake --in-place --remove-all-unused-imports -r src tests

echo "==> isort"
poetry run isort src tests

echo "==> black"
poetry run black src tests

echo "==> flake8"
poetry run flake8 src tests
